project:
  type: website
  output-dir: docs

website:
  title: "CSCI 4907"
  navbar:
    # background: primary
    # foreground: secondary
    # fontcolor: black
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - policies.qmd
      - text: "Getting Started"
        menu:
          - href: install-editor.qmd
      - schedule.qmd
      - text: "Notes"
        menu: 
          - href: Week0.qmd 
          - href: Week1.qmd
          - href: Week2.qmd
          - href: Spring2023_MidtermProjects.qmd
          - href: Week3.qmd
          - href: Week3-Parmer-Lecture.qmd


      - weekly.qmd
      - resources.qmd
      - instructor.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true



