project:
  type: website
  output-dir: docs

website:
  title: "CSCI 4907"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - policies.qmd
      - weekly.qmd
      - resources.qmd
      - instructor.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



